
# A string used to distinguish different Supabase projects on the same host. Defaults to the working
# directory name when running `supabase init`.
project_id = "pifzapdqhaxgskypadws"

[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a view, table, or stored procedure. Limits payload size
# for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[studio]
# Port to use for Supabase Studio.
port = 54323

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
# Port to use for the email testing server web interface.
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "5MB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Configure email templates
[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Configure email templates for password auth.
[auth.email.template.invite]
subject = "You have been invited"
content_path = ""

[auth.email.template.confirmation]
subject = "Confirm Your Signup"
content_path = ""

[auth.email.template.recovery]
subject = "Reset Your Password"
content_path = ""

[auth.email.template.magic_link]
subject = "Your Magic Link"
content_path = ""

# Configure SMS OTP templates
[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = false

[auth.sms.template.sms.verify]
content_path = ""

[auth.sms.template.sms.invite]
content_path = ""

[auth.sms.template.sms.confirmation]
content_path = ""

[auth.sms.twilio]
account_sid = ""
auth_token = ""
service_id = ""

# Configure the function that runs when a user clicks on the unsubscribe link in emails.
[auth.user.privacy]
unsubscribe_redirect_url = ""

# Set up Realtime service
[realtime]
enabled = true

# Configure functions for the Functions API.
[functions]
[functions.process-mpesa-payment]
verify_jwt = false
[functions.mpesa-callback]
verify_jwt = false

# Configure Postgres extensions.
[postgres.extensions]
[postgres.extensions.pg_graphql]
schema = "graphql_public"
version = "1.2.0"
enabled = true
[postgres.extensions.pg_vector]
version = "0.4.1"
enabled = false

# Allow tables to be created with the pgcrypto extension
[postgres.extensions.pgcrypto]
enabled = true

# Configure Storage.
[storage]
[storage.uploads]
enabled = true

# Configure one or more tables to store uploaded files.
# [storage.upload_tables]
# [storage.upload_tables.profiles]
# enabled = true
